### ISSUE TITLE
Error: "message": "Object.values is not a function"

### ISSUE THREAD

**Issue by parhelium** [APIs-guru/graphql-faker#1]
It looks like `graphql-faker@1.1.0` is totally broken.
Whatever I do always receive message:
```
"message": "Object.values is not a function"
```

![](http://g.recordit.co/dt4rUdSRjD.gif)

What I'm doing wrong ?

**Comment by RomanGotsiy** [comment]
@parhelium should be fixed now (via https://github.com/APIs-guru/graphql-faker/commit/ad2843db79ab9dfc97c483cb132da87e50f3dbce). Update to the latest `v1.1.1` version.

**Comment by parhelium** [comment]
@RomanGotsiy it is working now! Thanks for quick fix :)
👍
