### ISSUE TITLE
Lorempixel.com is always down

### ISSUE THREAD

**Issue by Adarshjain** [APIs-guru/graphql-faker#101]
Lorempixel.com is always down, can you move the URL to something else or make it configurable

**Comment by IvanGoncharov** [comment]
@Adarshjain Thanks for reporting it's an issue with `faker.js`:
https://github.com/Marak/faker.js/issues/364
Let's see if it will be fixed in a reasonable time.

**Comment by IvanGoncharov** [comment]
Fixed in 682affd21b1d86cadd6d096b32ab6fe971503067

**Comment by IvanGoncharov** [comment]
@Adarshjain Released as `graphql-faker@2.0.0-rc.18` 🎉
