### ISSUE TITLE
Voyager tab

### ISSUE THREAD

**Issue by mac2000** [APIs-guru/graphql-faker#103]
Will be so nice to have an voyager tab side by side with editor and playground, so I can not only prototype my schema but also visualize it

Seems to be doable, in my understanding it will be one more dependency to editor and addition of tab to index.ts with Voyager component being added

But immediately after adding graphql-voyager editors build broke with bazillion of errors complaing that 

```
ERROR in [at-loader] ./node_modules/@types/react/index.d.ts:3634:19
    TS2320: Interface 'IntrinsicClassAttributes<T>' cannot simultaneously extend types 'ClassAttributes<T>' and 'ClassAttributes<T>'.
  Named property 'ref' of types 'ClassAttributes<T>' and 'ClassAttributes<T>' are not identical.
```

At moment I'm even not sure from where to begin to fix that

**Comment by mac2000** [comment]
Managed to deal with errors above by upgrading react related packages to 16

Then got an issue `Cannot find namespace 'SvgPanZoom'.` which already [mentioned](https://github.com/APIs-guru/graphql-voyager/issues/91) in voyager repo  which indeed were fixed by suggested [workaround](https://github.com/APIs-guru/graphql-voyager/issues/91#issuecomment-427160595)

So all we need to do from now on:

1. Add voyager as a dependency to both server and editor

2. In server add 

```ts
app.use('/voyager', voyagerMiddleware({ endpointUrl: '/graphql' }));
app.use('/voyager.worker.js', express.static(path.join(__dirname, '../node_modules/graphql-voyager/dist/voyager.worker.js')));
```

3. In editor one more icon and tab like this one:

```ts
<div className={classNames('tab-content', {'-active': activeTab === 2,})}>
{this.state.schema && (
  <Voyager introspection={e => this.graphQLFetcher({query: e})} hideSettings={activeTab !== 2} />
)}
</div>
```

And we got desired tab with voyager

![image](https://user-images.githubusercontent.com/88868/82724716-b61a3680-9ce0-11ea-8948-c2d542704ddf.png)

**Comment by IvanGoncharov** [comment]
@mac2000 Looks great 👍 

> Managed to deal with errors above by upgrading react related packages to 16

It would be great if you submit this as a separate change.

> Then got an issue Cannot find namespace 'SvgPanZoom'. which already mentioned in voyager repo which indeed were fixed by suggested workaround

If you know how to fix it in Voyager repo I would gladly accept PR there.

**Comment by IvanGoncharov** [comment]
@mac2000 I reviewed #112 and it looks great 👍 
I made a few small changes on `master` that you need to accommodate other than that this feature looks ready to be merged.
Can you please reopen #112 or create a new PR?
