### ISSUE TITLE
Q: Is there any way to restrict schema change

### ISSUE THREAD

**Issue by Antiarchitect** [APIs-guru/graphql-faker#104]
Is there any way to restrict extending the schema (when using the --extend option) and allow to only fake data?

**Comment by IvanGoncharov** [comment]
@Antiarchitect Not sure I understand this question.
Can you give examples of SDL that you want to restrict?
Also please explain your use case in more detail.

**Comment by Antiarchitect** [comment]
@IvanGoncharov 
We are trying to use graphql-faker as a proxy to our real graphql API and want simple mocking. So we want to restrict of changing/adding new types and stuff and allow only fake the data.

**Comment by IvanGoncharov** [comment]
@Antiarchitect So if you can't change types or add new types what you are doing with a proxy?
If you want to just mock server you can dump server's introspection as SDL and run it without `--extend`.

**Comment by Antiarchitect** [comment]
Ok, thank you @IvanGoncharov
