### ISSUE TITLE
Cannot extend Mutation

### ISSUE THREAD

**Issue by slavovojacek** [APIs-guru/graphql-faker#18]
Hi! We've been struggling with this for quite a while now, so thought I'd try and ask for help.

Our use-case is simple. Extend an existing schema, and implement new Mutations and Queries. While extending the original Query type works perfectly fine for us, as soon as we try extending the original _Mutation_ type, we get strange errors, possibly related to how the merge is being done and the resulting AST parsed / constructed. Please note we only get this result when using variables; sending hard-coded values works just fine.

We _have_ done some investigation and it appears that the culprit is this method https://github.com/APIs-guru/graphql-faker/blob/master/src/proxy.ts#L122. Unfortunately, this is where we run out of depth, as we currently don't have the bandwidth to study the `visit` method / API properly. 

If anyone here has enough insight on this, it would be awesome if you could help us out. Any input and / or advice is greatly appreciated :)

**Our "extend"**

```graphql
type Car {
  id: String @fake(type: uuid)
  ownerName: String @fake(type: fullName)
}

input NewCarInput {
  ownerName: String!
}

extend type Mutation {
  createCar(input: NewCarInput!): NewCar!
}
```

**Our mutation**

```graphql
mutation CreateCar($input: NewCarInput!) {
  createCar(input: $input) {
    id
  }
}
```

**Result**

```son
{
  "errors": [
    {
      "message": "400 Bad Request\n{\"errors\":[{\"message\":\"Unknown type \\\"NewCarInput\\\". Did you mean ... ?\",\"locations\":[{\"line\":1,\"column\":28}]},{\"message\":\"Variable \\\"$input\\\" is never used in operation \\\"CreateCar\\\".\",\"locations\":[{\"line\":1,\"column\":20}]}]}"
    }
  ]
}
```

**Comment by IvanGoncharov** [comment]
@slavovojacek This day has come 😢
I hide this problem under [TODO](https://github.com/APIs-guru/graphql-faker/blob/master/src/proxy.ts#L148), here is real problem:
> "message\":\"Variable \\\"$input\\\" is never used in operation \\\"CreateCar\\\".

If some variable used only inside faked part it still presented in the query to the origin server and it complains about an unused variable. 

Will try quick fix it by inlining all parameters inside the query.

**Comment by IvanGoncharov** [comment]
@slavovojacek Also notice the second error in your sample. Then you define new mutation you reference `NewCar` type but you only define `Car` type.

**Comment by IvanGoncharov** [comment]
@slavovojacek I fixed the unused variables issue and released v1.2.2.
Does it solve your issue?

**Comment by slavovojacek** [comment]
@IvanGoncharov Just tested it, works perfectly! Thanks a lot 👍 

PS. I fixed the typo (`NewCar` / `Car` type) in the description, thanks for pointing it out.

**Comment by IvanGoncharov** [comment]
@slavovojacek Great 🎉
If you have any other suggestion would be happy to help.

P.S. It looks like you use Faker to its maximum since nobody report this issue previously.
It would be great if you share your experience with it. Please consider writing a blog or giving a talk on your local API/JS/GraphQL meetup.

**Comment by slavovojacek** [comment]
Hi @IvanGoncharov! Thanks for your reply and I am of course more than happy to share any feedback. I have already done a number of presentations and talks on how and why we use GQL Faker – in the SE Asia region, where I am currently based.

On another note, however we've just found out, that it is now impossible to run a parameterised query, defined in the original schema.

So let's say we extend our schema, which has `card(id: ID!): Card`, then we attempt:

```gql
query ($id: ID!) {
  card(id: $id) {
    id
  }
}
```

And this is the error we get:

```
{
  "errors": [
    {
      "message": "400 Bad Request\n{\"errors\":[{\"message\":\"Variable \\\"$id\\\" is not defined.\",\"locations\":[{\"line\":2,\"column\":12},{\"line\":1,\"column\":1}]}]}"
    }
  ]
}
```

As before, when `id` is hardcoded, it works correctly, e.g.

```gql
query {
  card(id: 1) {
    id
  }
}
```

Can you please advise?

**Comment by IvanGoncharov** [comment]
> I have already done a number of presentations and talks on how and why we use GQL Faker – in the SE Asia region, where I am currently based.

Thanks a lot 👍 Do you have any video online or a slide deck?

> On another note, however we've just found out, that it is now impossible to run a parameterised query, defined in the original schema.

That's why I need to add test suite to prevent regressions like that 😞 
Meanwhile, I fixed regression and published `v1.2.3`.

BTW. Are you planning on coming to [GraphQL Summit](https://summit.graphql.com/)?
Would be great to see you there.

**Comment by slavovojacek** [comment]
> Thanks a lot 👍 Do you have any video online or a slide deck?

For now only pictures of me introducing GraphQL during JakartaJS Meetup, sorry!

> Meanwhile, I fixed regression and published v1.2.3.

I tried installing latest (1.2.3), however the issue seems to still be occurring.

As for the Summit, I'd love to, just not sure I can _actually_ make it due to my current engagement in Indonesia ([flight] time is the issue). But one never knows..

**Comment by slavovojacek** [comment]
To add to your question, I did a number of internal presentations with the client and onsite teams, so no documentation there, sorry... If I get a chance to present in the future, and there is some documentation, I will let you know.

**Comment by IvanGoncharov** [comment]
> I tried installing latest (1.2.3), however the issue seems to still be occurring.

Can you please post schema extension and query here?

**Comment by slavovojacek** [comment]
There is no schema extension other than the default 

```graphql
extend type Query {
  pet: Pet
}

type Pet {
  name: String @fake(type:firstName)
  image: String @fake(type:imageUrl, options: {imageCategory:cats})
}
```

The query is

```javascript
query ($id: ID!) {
  card(id: $id) {
    id
  }
}
```

Card being only defined on the original schema.

**Comment by IvanGoncharov** [comment]
@slavovojacek I can't reproduce it 😞 
Can you please copy paste error message from `1.2.3`. Maybe it's different now?
Can you try to reproduce it with `http://swapi.apis.guru` instead of your api?

Just to be sure can you please run `$ npm list -g | grep graphql-faker` to make sure you install new version globally?

**Comment by slavovojacek** [comment]
![graphql-faker](https://user-images.githubusercontent.com/4658565/29901072-2c8adca2-8e20-11e7-86dd-af14c949f72a.png)

^^ Oops! My bad, I assumed `1.2.3` was installed but in fact it wasn't.

It now works flawlessly. Many thanks again. I might look into contributing to this project in the nearby future. Happy to look into testing, and all sorts of other things – I love TypeScript you see? :)

**Comment by IvanGoncharov** [comment]
@slavovojacek Great! Tests will be great especially some snapshot testing will be great.

My main goal at the moment is to stop using custom forks of `graphql-js` and `express-graphql`.
So I'm working on pushing necessary functionality into mainlines testing is my second priority after that.

**Comment by codenakama** [comment]
Hey guys, I am having this issue or something similar. Am I doing anything wrong?

```
export const GET_ACTIVITIES_BY_LOCATION = gql`
    query activities($locationId:Int!) {
        activities(locationId: $locationId) {
        image
        id
        name
        kind
        bookingsCalID
        staffingCalID
        spaces{
            id
            name
            locationId
            activities {
            id
            }
            calId
        }
        bookableProducts {
            id
            name
            duration
            rolesRequired
        }
        }
  }
`
```

the error I get is 
`400 Bad Request
{"errors":[{"message":"Variable \"$locationId\" is never used in operation \"activities\".","locations":[{"line":1,"column":18}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Variable \"$locationId\" is never used in operation \"activities\".","`

**Comment by IvanGoncharov** [comment]
@codenakama Thanks for reporting this issue 👍 
Fixed in `2.0.0-rc.5` 🎉 
Can you please test it?

**Comment by codenakama** [comment]
@IvanGoncharov can confirm it's fixed! thank you very much for the swift resolution. I discovered this tool just a few hours ago and its super useful.

**Comment by zsid** [comment]
I am really struggling to find an example that would work. My mutation is 
```
export const CHANGE_TIME = gql`
  mutation ChangeMaterControl(
    $model: MOVIE
    $action: PAUSED
    $value: Boolean
  ) {
    masterControl(model: $model, set: { action: $action, value: $value }) {
      success
    }
  }
`;
```

Can you help me @IvanGoncharov? I am really struggling with finding examples with mutations

**Comment by IvanGoncharov** [comment]
@zsid `$model: MOVIE` looks suspicious? Are you sure that `MOVIE` is a type name and not enum value?
You need to specify variable type when you define it and it can't be value it should be the name of the type.
So did you meant something like this instead:
```graphql
  mutation ChangeMaterControl($value: Boolean) {
    masterControl(model: MOVIE, set: { action: PAUSED, value: $value }) {
      success
    }
  }
````
