### ISSUE TITLE
Customer scalar input bug

### ISSUE THREAD

**Issue by chollier** [APIs-guru/graphql-faker#20]
Hey first off, thanks for the awesome work! We've been wanting to do GraphQL First development for a while and your project is definitely a game changer in our workflows!

A bug must have been introduced between 1.2.1 and 1.2.2, I have a query that works with 1.2.1 and not 1.2.2. Here is the (formatted) error returned: 
```javascript
{
  errors: [
    {
      message:
        'Variable "$input" got invalid value {"endDate":"2017-09-03","startDate":"2017-08-28","brandIds":[],"displayDefinitionIds":[],"regions":[],"retailerIds":[],"storeIds":[],"layerGroupingSets":[],"attributeValueSets":[]}.\nIn field "startDate": Expected type "Date", found "2017-08-28".\nIn field "endDate": Expected type "Date", found "2017-09-03".',
      locations: [{ line: 1, column: 64 }]
    }
  ]
};
```

our schema contains this line:
```graphql
scalar Date
```

**Comment by IvanGoncharov** [comment]
@chollier Thank you for reporting this issue 👍 
I published `1.2.4` with the fix included.

Need to add tests to prevent stupid regressions like this one 🤦‍♂️
