### ISSUE TITLE
Very cool!

### ISSUE THREAD

**Issue by mpicard** [APIs-guru/graphql-faker#31]
Awesome job guys, this is a super cool tool! :+1:

**Comment by IvanGoncharov** [comment]
@mpicard Thanks for motivating comment 😄 and a star ⭐️ 

Please consider speaking on local meetup about it or writing a blog post.
Also, check out our other GraphQL projects:
https://github.com/APIs-guru/graphql-voyager
https://github.com/APIs-guru/graphql-apis
https://github.com/APIs-guru/graphql-lodash

**Comment by peteruithoven** [comment]
While I totally agree with the content, shouldn't this issue be closed?

**Comment by IvanGoncharov** [comment]
@peteruithoven Let's keep it!
I think it's like a user testimony for this project.

**Comment by mpicard** [comment]
I’ll close since there is no “issue” :P just wanted to leave my 2c

**Comment by IvanGoncharov** [comment]
@mpicard Thanks, this issue motivated me a lot!
