### ISSUE TITLE
Custom error fields are not proxied

### ISSUE THREAD

**Issue by caseycs** [APIs-guru/graphql-faker#34]
In order to handle forms validation I'm going to use additional fields inside regular errors (to mention exact fields and failed validation rules), however looks like additional field are not proxied at all.

For example: original endpoint gives me response:

```
{
  "errors": [
    {
      "message": "An unknown error occurred.",
      "category": "auth",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "authUser"
      ]
    }
  ],
  "data": {
    "authUser": null
  }
}
```

e.g. with custom field `category`, and while proxying same query via faker - just

```
{
  "data": {
    "authUser": null
  },
  "errors": [
    {
      "message": "An unknown error occurred.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "authUser"
      ]
    }
  ]
}
```

So my custom `category` field is lost. 

What do you think about proxying complete error?

**Comment by IvanGoncharov** [comment]
@caseycs Should be pretty easy to fix, I will try to fix it this weekend.

**Comment by IvanGoncharov** [comment]
@caseycs Fixed in `1.6.0` 📦 
Can you please test it?

**Comment by caseycs** [comment]
@IvanGoncharov thanks a lot! It's working actually - when I clone the repo and execute `./node_modules/.bin/ts-node src/index.ts --port 16666 --extend http://dev.project.domain/graphql`

However when i'm doing 
```
> npm i --global graphql-faker
/usr/local/bin/graphql-faker -> /usr/local/lib/node_modules/graphql-faker/dist/index.js
+ graphql-faker@1.6.0
added 121 packages in 6.131s
~> which graphql-faker
/usr/local/bin/graphql-faker
~> graphql-faker --version
1.6.0
~> graphql-faker  --port 16666 --extend http://dev.project.domain/graphql
```

I see same output as before the patch. Node stack is quite new for me, so i'm very confused.

**Comment by RomanGotsiy** [comment]
@caseycs, seems @IvanGoncharov forgot to compile typescript before publishing to npm.
I've just republished it as graphql-faker@1.6.1. Could you verify it works fine now?

**Comment by caseycs** [comment]
@RomanGotsiy thanks for the fast response!

```
npm i --save-dev graphql-faker@1.6.1
~/x/y:master> node_modules/.bin/graphql-faker
Failed to execute process 'node_modules/.bin/graphql-faker'. Reason:
exec: Exec format error
The file 'node_modules/.bin/graphql-faker' is marked as an executable but could not be run by the operating system.
```

Looks like something went wrong during compilation ;-)

I noticed that executable file became very different:
[graphql-faker.1.6.0.txt](https://github.com/APIs-guru/graphql-faker/files/1499260/graphql-faker.1.6.0.txt)
[graphql-faker.1.6.1.txt](https://github.com/APIs-guru/graphql-faker/files/1499261/graphql-faker.1.6.1.txt)

**Comment by RomanGotsiy** [comment]
oops 🙈 , try `1.6.2` plz

**Comment by caseycs** [comment]
Works perfectly now! Thanks a lot.
