### ISSUE TITLE
extending amount of results returned on fake response

### ISSUE THREAD

**Issue by idkjs** [APIs-guru/graphql-faker#40]
Is it possible pass query variable for 20 results, for example?

**Comment by IvanGoncharov** [comment]
@idkjs I'm confused. Can you please provide more detail description.
Do you want to make arrays bigger or something else?

**Comment by idkjs** [comment]
I guess should add and a (count:Int) variable to the Companies query and see what happens. I was just trying to get more than two results back from the default companies query

**Comment by OlzhasAlexandrov** [comment]
Duplicate of https://github.com/APIs-guru/graphql-faker/issues/12
