### ISSUE TITLE
Arguments order issue?

### ISSUE THREAD

**Issue by peteruithoven** [APIs-guru/graphql-faker#49]
The Readme mentions:
```
graphql-faker [options] [IDL file]
```
But GraphQL-faker only seems to accept the file when it's specified before the other options. So this works:
```
graphql-faker ./temp.faker.graphql --extend http://localhost:8091/graphql --forward-headers Authorition 
```
This doesn't work:
```
graphql-faker --extend http://localhost:8091/graphql --forward-headers Authorition ./temp.faker.graphql
```

Is there any way to have it also accept the file when it's defined after the options? The benefit would be that it becomes possible to create an npm script and pass in a specific file as argument. 

Could we use [positional](https://github.com/yargs/yargs/blob/HEAD/docs/api.md#positionalkey-opt) for this? 
Could we allow specifying it as a explicit `--file` option?

**Comment by IvanGoncharov** [comment]
@peteruithoven Thanks for reporting 👍 
Looking into it right now 🔎 🐞

**Comment by IvanGoncharov** [comment]
@peteruithoven I just published `1.7.4` which cleanups Yargs code.

> graphql-faker --extend http://localhost:8091/graphql --forward-headers Authorition ./temp.faker.graphql

Should be:
> graphql-faker --extend http://localhost:8091/graphql --forward-headers Authorition -- ./temp.faker.graphql

Note: `--` after `--forward-headers Authorition` it's required since `forward-headers` accepts space separated list of header names so without `--` Yargs thinks that `./temp.faker.graphql` is another header.

**Comment by peteruithoven** [comment]
Thanks for looking into this so quickly! This totally fixes my npm script challange. 
We can now simply add a script like:
```
  "scripts": {
    "start-faker": "graphql-faker --extend http://localhost:8091/graphql --forward-headers Authorization --"
  }
```
And call it with something like: `npm run start-faker -- faker.graphql`

**Comment by peteruithoven** [comment]
I though pointing to the [relevant Yargs docs](https://github.com/yargs/yargs/blob/master/docs/api.md#array) would be a bit to technical?

**Comment by IvanGoncharov** [comment]
@peteruithoven If you switch places `--extend` and `--forward-headers` you can omit `--` both in `package.json` and npm call.

**Comment by peteruithoven** [comment]
Good point. I'll try including that in https://github.com/APIs-guru/graphql-faker/pull/50
