### ISSUE TITLE
Forward-headers and provided headers.

### ISSUE THREAD

**Issue by deftomat** [APIs-guru/graphql-faker#51]
Hi, first of all, this package is AWESOME.

However, we have a problem to make it works with AWS AppSync.
The problem is, that AppSync will deny all connections without `Authorization` header. So, we created a small script, which will obtain a JWT from AWS and then starts `graphql-faker` with that token.

Until this, everything is ok. Then when our web client tries to access a `graphql-faker`'s endpoint, it also provides a different JWT as you can be logged in as any user. However, faker will access an AppSync with a JWT provided at start.

**In another words:** 
Is it possible to provide a `--header "Authorization: IDTOKEN"` alongside with `--forward-headers` and force `graphql-faker` to use a provided *Authorization* header or forward *Authorization* header when it is provided by client.

We are using this command to start it:
```
graphql-faker --forward-headers Authorization --header "Authorization: IDTOKEN" --extend https://abc.amazonaws.com/graphql ./ext-dev.graphql
```

**Comment by IvanGoncharov** [comment]
@deftomat Headers are compared in lower-case so following command should work:
```sh
graphql-faker --forward-headers authorization --header "authorization: IDTOKEN" --extend https://abc.amazonaws.com/graphql ./ext-dev.graphql
```
Can you please test it?
If it works I will fix Faker to do this automatically.

**Comment by IvanGoncharov** [comment]
@deftomat Change was really small so I just published `1.7.5` now your original command should work.
Can you please test it?

**Comment by deftomat** [comment]
@IvanGoncharov 

AWESOME, `1.7.5` is working. 

Thanks.

**Comment by ebisbe** [comment]
@deftomat Can you share you little script to do the trick? From what I read here it's not in the repo right?

**Comment by deftomat** [comment]
@ebisbe Hi, it's a long time ago and we are not using it anymore. We switched from AppSync to Apollo in lambdas, which already includes the faker/mocks as AppSync was a paint for us 😞
