### ISSUE TITLE
What was the changes in the graphql branch?

### ISSUE THREAD

**Issue by lucasfeliciano** [APIs-guru/graphql-faker#52]
Hello, I forked this branch for the use here in the company and I decided to use `apollo-server` instead of `graphql-express`.

The reason is that we use batched queries and `apollo-server` has this feature out of the box.

So I saw that you forked the graphql repositorie to implement some changes related to the directives.

`github:apis-guru/graphql-js#directives-fork-dist`

However I can't find this branch in the forked repo to see what were the changes.

I think the changes was to create/overwrite directives but now graphql provide new feature to do that: https://www.apollographql.com/docs/graphql-tools/schema-directives.html

And thats how I want to approach, but I need to know the changes that you made to continue with this :)

**Comment by IvanGoncharov** [comment]
@lucasfeliciano See here: https://github.com/APIs-guru/graphql-faker/issues/41#issuecomment-372969321

**Comment by IvanGoncharov** [comment]
> I think the changes was to create/overwrite directives but now graphql provide new feature to do that: apollographql.com/docs/graphql-tools/schema-directives.html

@lucasfeliciano It's apollo specific implementation and I try to keep this project vanilla GraphQL.

> Hello, I forked this branch for the use here in the company and I decided to use apollo-server instead of graphql-express. The reason is that we use batched queries and apollo-server has this feature out of the box.

I plan to add support of batched queries to https://github.com/graphql/express-graphql in the near future.

**Comment by IvanGoncharov** [comment]
@lucasfeliciano I finally migrated away from forked `graphql` and released 2.0.0-rc.1 📦 with this change.
If you have time can you please test it?
