### ISSUE TITLE
How to get a random value from an ENUM?

### ISSUE THREAD

**Issue by sneko** [APIs-guru/graphql-faker#56]
Hi!

I would like to fake the following `type` field:
```
type Phone {
  type: PhoneType @fake(???????????????)
  ...
}

enum PhoneType {
  HOME
  MOBILE
}
```

And I was wondering if your library is able to randomly choose one value of the ENUM without me writing anything? Or should I have to write:
```
  type: PhoneType @examples(values: ["HOME", "MOBILE"])
```

Thank you,

**Comment by IvanGoncharov** [comment]
> And I was wondering if your library is able to randomly choose one value of the ENUM without me writing anything? 

@sneko You don't need to specify `@fake` or `@example` everything should work by default.
