### ISSUE TITLE
How would you generate IDL based on existing graphql sever?

### ISSUE THREAD

**Issue by kuncevic** [APIs-guru/graphql-faker#57]
Is there anyway I can generate IDL based on an existing graphql server? This way it would save a lot on typing the things manually.

Any ideas?

**Comment by IvanGoncharov** [comment]
@kuncevic You can try this tool:
https://github.com/Yoctol/fetch-graphql-schema
https://github.com/Yoctol/fetch-graphql-schema/blob/master/src/index.js
