### ISSUE TITLE
Error when implementing multiple interfaces

### ISSUE THREAD

**Issue by steebchen** [APIs-guru/graphql-faker#67]
The editor complains about the `&` operator when implementing multiple interfaces while it's valid GraphQL:

![Selection_076](https://user-images.githubusercontent.com/5013932/57489200-9b337a80-72b5-11e9-8197-5c74bbf489aa.jpg)

**Comment by sriganeshharitz** [comment]
Any fix for this?

**Comment by IvanGoncharov** [comment]
@sriganeshharitz I'm working on this.
As a temporary fix, you can use the old syntax for listing interfaces:
```graphql
type Viewer implements IUser IViewer {
  # ...
}
```
Also, you can do this by automatically removing all `&` before running faker.

**Comment by steebchen** [comment]
A comma works too `type Viewer implements IUser, IViewer {`, although I'm not sure if this is the official previous syntax but I have seen it several times.

**Comment by IvanGoncharov** [comment]
@steebchen @sriganeshharitz I released 2.0.0-rc.1 📦 that fix this issue.
If you have time can you please test it?
