### ISSUE TITLE
[Dev issue] Can't resolve '../fake_definition' in '/path/to/repo/graphql-faker/src/editor'

### ISSUE THREAD

**Issue by caiyongmin** [APIs-guru/graphql-faker#78]
first of all, thank you for creating such a amazing project.

this is an issue about development, when i execute `npm run build:all`, i got some error message:

```bash
ERROR in ./index.tsx
Module not found: Error: Can't resolve '../fake_definition' in '/path/to/repo/graphql-faker/src/editor'
 @ ./index.tsx 28:24-53
 @ multi ./index.tsx

ERROR in [at-loader] ./index.tsx:9:42
    TS2307: Cannot find module '../fake_definition'.
Child extract-text-webpack-plugin:
```

and when open the `src/index.ts` and `src/editor/index.tsx`，also get same error.

is something i am missing?

**Comment by IvanGoncharov** [comment]
@caiyongmin Thanks for reporting 👍 
The classic mistake of forgetting to `git add` new file 🤦‍♂

**Comment by caiyongmin** [comment]
You're welcome!

How about use husky hooks to avoid the similar issue?

**Comment by IvanGoncharov** [comment]
@caiyongmin Thanks for advice 👍 I will look into husky but I think classic solution of CI + tests would be a good first step.

I already applied for GitHub Action Beta on APIs.guru account and still waiting for them to enable it for us.
I also need to figure out how to write feature tests for a CLI app that works with FS:
https://github.com/APIs-guru/graphql-faker/issues/7
