### ISSUE TITLE
Return passed-in value from mutation

### ISSUE THREAD

**Issue by LeeroyJenks** [APIs-guru/graphql-faker#80]
Thank you so much for this tool. It's really made it a lot easier for me to work in tandem with our back end team here and hopefully get projects out quicker.

I wanted to be able to have a mutation return the passed-in value. 

For example, if I have a type `Lead`:
```GraphQL
type Lead {
  id: ID @fake(type: uuid)
  status: String @examples(values:[ "New Lead", "In Communication" ])
}
```

And I extend my `QueryRoot` like so:
```GraphQL
extend type QueryRoot {
	leads: [Lead] @listLength(min: 0, max:20)
}
```

And then extend my `MutationRoot`:
```GraphQL
extend type MutationRoot {
  update_lead_status(lead_id:ID! status: String!): Lead
}
```

When I run the mutation:
```GraphQL
mutation {
  update_lead_status(id: "2fe0df37-955d-4de2-bd50-d1176a1bd4c4" status: "New Lead") {
    id
    status
  }
}
```

It'll still return a random `id` and `status`.  Is there a way to have it return the passed-in values instead? I want to mimmic a successful mutation of values and check some Apollo caching, which would at the very least require the id to be returned.

thanks!

**Comment by IvanGoncharov** [comment]
@LeeroyJenks Thanks a lot for detail example 👍 
Sorry for the delay, implemented in `2.0.0-rc.13` 📦 
Can you please test it?

**Comment by LeeroyJenks** [comment]
@IvanGoncharov that was perfect, thank you! Works flawlessly now. 

![image](https://user-images.githubusercontent.com/3408364/67234775-baf9cd80-f413-11e9-9531-ab0a82ebe175.png)

Although now when I set up a fake time like so:
`submitted_at: Time @fake(type: pastDate)`
I get an error on save:
`Unknown type "Time".`

Am I doing something wrong? Should I open another issue?

Thanks again! Extremely useful tool

**Comment by IvanGoncharov** [comment]
@LeeroyJenks GraphQL doesn't define any type beyond `Int`, `Float`, `ID`, `String` and `Boolean`. For any other scalar type you need to define it:
```
scalar Time
```

**Comment by LeeroyJenks** [comment]
I guess it was working before because I was extending an existing graphql endpoint.

Thank you!

**Comment by alecrae** [comment]
@IvanGoncharov this fix appears to be affecting mutations that are not faked or have fields that are faked ie passed straight through to a real graphql backend, I think it should only be applied to faked fields?

**Comment by IvanGoncharov** [comment]
@alecrae Can you please report it as a separate issue and provide an example?

**Comment by alecrae** [comment]
@IvanGoncharov sure thing, my colleague has done so in #97
