### ISSUE TITLE
Read in exported string

### ISSUE THREAD

**Issue by chookie** [APIs-guru/graphql-faker#9]
faker is awesome, thanks for the work.  I tend to have my schema in a template string and export it so it would be great if I could use that file directly then when I edit it in faker it also gets updated directly in my project.  Or do you know a way to achieve this already?  I was starting to create something similar to this then saw your project.  I am happy to do it if you don't have time as makes more sense to contribute to your project then start another.  

An example of the file format is 
```javascript
'use strict';

export default `
  type Company {
    # This is the company name
    name: String @fake(type:companyName)
    # A test by Alison
    test: String @fake(type:productCategory)
    industry: String @examples(values: ["IT", "Manufactury", "Medicine", "Media"])
    employees: [Employee!]
  }

  type Employee {
    firstName: String @fake(type: firstName, locale:en_CA)
    lastName: String @fake(type: lastName, locale:en_CA)
    address: String @fake(type:streetAddress, options: { useFullAddress: true })
    subordinates: [Employee!]
    company: Company
  }

  type Query {
    employee(id: ID): Employee
    company(id: ID): Company
    allCompanies: [Company!]
  }
`;

```

Also did you mean to have 'Manufactury' instead of 'Manufacturing' ?

**Comment by IvanGoncharov** [comment]
> faker is awesome, thanks for the work.

@chookie Thank you for kind words.

> Also did you mean to have 'Manufactury' instead of 'Manufacturing' ?

Good catch👍 I fixed this typo and published a new version.

>  I tend to have my schema in a template string and export it so it would be great if I could use that file directly then when I edit it in faker it also gets updated directly in my project. Or do you know a way to achieve this already?

It would be hard to implement, especially updating `.js` file from our IDL editor.
Alternatively, you can extract IDL into a separate file and still use it in JS code, e.g:
1) If you use it inside `node.js` project you can do the following:
```
import { readFileSync } from 'fs';
import { join } from 'path';

let IDL = readFileSync(join(__dirname, './schema.idl'), 'utf-8');
export default IDL;
```
2) In case if you use Webpack you can achieve the same with `raw-loader`:
https://webpack.js.org/loaders/raw-loader/

If none of them works we can try to figure out something else.

**Comment by chookie** [comment]
raw loader works perfectly and addresses my request.  Thank you.

**Comment by IvanGoncharov** [comment]
@chookie Awesome! 🎉
