### ISSUE TITLE
Docs work but all queries return 'Cannot read property 'x' of undefined'

### ISSUE THREAD

**Issue by brasilikum** [APIs-guru/graphql-faker#91]
Hey, I updated to faker `graphql-faker@2.0.0-rc.14`.
Since then all queries return an undefined error. For example
```gql
query {
  profile {
    id
  }
}
```

```json
{
  "errors": [
    {
      "message": "Cannot read property 'profile' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "profile"
      ]
    }
  ],
  "data": {
    "profile": null
  }
}
```

The strange thing is that the editor and the docs still work correctly.
I tried downgrading but the error persists.

Any Idea what could be causing this?

**Comment by IvanGoncharov** [comment]
@brasilikum Thanks for reporting 👍 
I released `v2.0.0-rc.15` 📦 🎉 
Can you please try it?

**Comment by brasilikum** [comment]
It works again! Thank you very much. 
Would you be interested if I tried to set up some Github actions or some other CI to do some automated testing?

**Comment by IvanGoncharov** [comment]
@brasilikum Yes this would be great 👍 
The big challenge is that it should be CLI tests.
More details here: https://github.com/APIs-guru/graphql-faker/issues/7#issuecomment-523747852
