### ISSUE TITLE
Image width and hight switched?

### ISSUE THREAD

**Issue by brasilikum** [APIs-guru/graphql-faker#92]
Hey,
For me, imageHeight and imageWidth are switched. Can someone verify this?

If this is a Bug, the question is of course how to correct it without breaking peoples use of the API. Maybe deprecate them and add `imgHeight` and `imgWidth`?

**Comment by IvanGoncharov** [comment]
@brasilikum Thanks for reporting 👍 
Fixed in `2.0.0-rc.16` 📦 
Can you please test it?
