### ISSUE TITLE
Status code 500 on Error when extending

### ISSUE THREAD

**Issue by gouvermxt** [APIs-guru/graphql-faker#96]
On error situations, my GraphQL server is configured to return a 200 status code along with a JSON with an "errors" key containing an array. However, when using graphql-faker bridge, it changes the status code to 500, which breaks my frontend. 

I don't know if that's a bug or on purpose.

**Comment by IvanGoncharov** [comment]
@gouvermxt Thanks for reporting 👍 
If you have non-null `data` in response it should be 200 if data is missing it should be 500. What's the value of `data` in your request?

**Comment by gouvermxt** [comment]
My error response does not contain the data field.

**Comment by IvanGoncharov** [comment]
@gouvermxt It's expected when `data` is missing and implemented in `express-graphql`.
ATM, we are working on standardizing GraphQL servers see:
https://github.com/APIs-guru/graphql-over-http
and this case should standardize as part of this process.
