### ISSUE TITLE
When a parameter has the same name as the returned field the return value is replaced

### ISSUE THREAD

**Issue by gabrielrinaldi** [APIs-guru/graphql-faker#97]
If you make a request like this:

```
mutation {
  login(email: "user@email.com", token: "SFMyNTY.g3QAAAACZAAEZGF0YX") {
    token
  }
}
```

And the mutation is not in the local SDL, it returns the same value that it was passed:

```
{
  "data": {
    "login": {
      "token": "SFMyNTY.g3QAAAACZAAEZGF0YX"
    }
  }
}
```

When instead it was supposed to return the new value coming from the server. 

This could be potentially related to the changes made when adding the feature request here: #80.

**Comment by alecrae** [comment]
@IvanGoncharov Fixed in PR #100
